/**
 * Script to generate preferred verses data with embedded verse text.
 * This allows consumers to use preferred verses without importing the full Tanach data (6.3 MB).
 *
 * Usage: npx tsx scripts/generate-preferred-with-text.ts
 */
import { data } from '../src/data.js';
import { preferredVerses } from '../src/preferred-verses.js';

interface EnrichedVerse {
  startLetter: string;
  endLetter: string;
  book: string;
  chapter: number;
  verse: number;
  text: string;
  bookHebrew: string;
  bookEnglish: string;
  notes?: string;
}

const enriched: EnrichedVerse[] = [];

for (const pv of preferredVerses) {
  const bookData = data[pv.book];
  if (!bookData) {
    console.warn(`Book not found: ${pv.book}`);
    continue;
  }

  const chapterData = bookData.chapters[pv.chapter];
  if (!chapterData) {
    console.warn(`Chapter not found: ${pv.book} ${pv.chapter}`);
    continue;
  }

  const verseData = chapterData.find(([v]) => v === pv.verse);
  if (!verseData) {
    console.warn(`Verse not found: ${pv.book} ${pv.chapter}:${pv.verse}`);
    continue;
  }

  const entry: EnrichedVerse = {
    startLetter: pv.startLetter,
    endLetter: pv.endLetter,
    book: pv.book,
    chapter: pv.chapter,
    verse: pv.verse,
    text: verseData[1],
    bookHebrew: bookData.meta.he,
    bookEnglish: bookData.meta.en,
  };

  if (pv.notes) {
    entry.notes = pv.notes;
  }

  enriched.push(entry);
}

// Generate the TypeScript file
const output = `/**
 * Preferred verses with embedded text for lightweight imports.
 * This file is auto-generated by scripts/generate-preferred-with-text.ts
 * DO NOT EDIT MANUALLY - run: npx tsx scripts/generate-preferred-with-text.ts
 *
 * This module contains ${enriched.length} preferred verses with their full text,
 * allowing consumers to look up preferred verses without importing the full Tanach data (6+ MB).
 */

export interface PreferredVerseWithText {
  /** Starting letter of the name */
  startLetter: string;
  /** Ending letter of the name */
  endLetter: string;
  /** Book name (transliterated) */
  book: string;
  /** Chapter number */
  chapter: number;
  /** Verse number */
  verse: number;
  /** Full Hebrew verse text */
  text: string;
  /** Hebrew book name */
  bookHebrew: string;
  /** English book name */
  bookEnglish: string;
  /** Notes or alternative information */
  notes?: string;
}

export const preferredVersesWithText: PreferredVerseWithText[] = ${JSON.stringify(enriched, null, 2)};
`;

// Write to src/preferred-verses-data.ts
import { writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const outputPath = resolve(__dirname, '../src/preferred-verses-data.ts');
writeFileSync(outputPath, output, 'utf-8');

console.log(`Generated ${outputPath} with ${enriched.length} enriched preferred verses.`);
